### PR TITLE
[Suggestion] Reverse punch and shift-punch functions on barrels

### PR DESCRIPTION
**Pull request by DarkYuan**
Changing litterally one variable to make it more in line with other mods' barrels

### CODE REVIEW

**Comment by DarkYuan** [comment]
Also I noticed that the version of Baubles that the master branch tried to build with was for 1.11

**Comment by maruohon** [comment]
Instead of just suddenly reversing this behavior for everyone, I'd rather like to add a client-side config option to select which way the player prefers this to work. That will need some changes to the event handling, and a custom packet or key action to be sent from the client for the clicks.

**Comment by DarkYuan** [comment]
I thought it would end up getting implemented that way. Sorry, I'm just learning forge modding and github both for the first time, and this was like my practice PR

**Comment by maruohon** [comment]
Yeah no problem. I'm just saying that I wouldn't want to do this simple one-line change to just suddenly reverse the behavior for everyone who has gotten used to the current way it works. And because the item extraction happens on the server side, but the config would be best done as a client-side option so that every player can individually change it the way they prefer it, it needs a bit more code to implement things that way.

**Comment by maruohon** [comment]
This was implemented in another commit.

**Pull request closed without merging**
